USE [master]
GO
/****** Object:  Database [ELCA_PIM_TEST]    Script Date: 10/6/2021 9:34:36 AM ******/
CREATE DATABASE [ELCA_PIM_TEST] 
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ELCA_PIM_TEST].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ELCA_PIM_TEST] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ELCA_PIM_TEST] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ELCA_PIM_TEST] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ELCA_PIM_TEST] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ELCA_PIM_TEST] SET ARITHABORT OFF 
GO
ALTER DATABASE [ELCA_PIM_TEST] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ELCA_PIM_TEST] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ELCA_PIM_TEST] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ELCA_PIM_TEST] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ELCA_PIM_TEST] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ELCA_PIM_TEST] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ELCA_PIM_TEST] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ELCA_PIM_TEST] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ELCA_PIM_TEST] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ELCA_PIM_TEST] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ELCA_PIM_TEST] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ELCA_PIM_TEST] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ELCA_PIM_TEST] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ELCA_PIM_TEST] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ELCA_PIM_TEST] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ELCA_PIM_TEST] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ELCA_PIM_TEST] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ELCA_PIM_TEST] SET RECOVERY FULL 
GO
ALTER DATABASE [ELCA_PIM_TEST] SET  MULTI_USER 
GO
ALTER DATABASE [ELCA_PIM_TEST] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ELCA_PIM_TEST] SET DB_CHAINING OFF 
GO
EXEC sys.sp_db_vardecimal_storage_format N'ELCA_PIM_TEST', N'ON'
GO
USE [ELCA_PIM_TEST]
GO
/****** Object:  Table [dbo].[EMPLOYEE]    Script Date: 10/6/2021 9:34:36 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EMPLOYEE](
	[ID] [numeric](19, 0) IDENTITY(1,1) NOT NULL,
	[VISA] [char](3) NOT NULL,
	[FIRST_NAME] [varchar](50) NOT NULL,
	[LAST_NAME] [varchar](50) NOT NULL,
	[BIRTH_DATE] [date] NOT NULL,
	[VERSION] [numeric](10, 0) NOT NULL,
 CONSTRAINT [PK_EMPLOYEE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[VISA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GROUP]    Script Date: 10/6/2021 9:34:36 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GROUP](
	[ID] [numeric](19, 0) IDENTITY(1,1) NOT NULL,
	[GROUP_LEADER_ID] [numeric](19, 0) NOT NULL,
	[VERSION] [numeric](10, 0) NOT NULL,
 CONSTRAINT [PK_GROUP] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PROJECT]    Script Date: 10/6/2021 9:34:36 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PROJECT](
	[ID] [numeric](19, 0) IDENTITY(1,1) NOT NULL,
	[GROUP_ID] [numeric](19, 0) NOT NULL,
	[PROJECT_NUMBER] [numeric](4, 0) NOT NULL,
	[NAME] [varchar](50) NOT NULL,
	[CUSTOMER] [varchar](50) NOT NULL,
	[STATUS] [char](3) NOT NULL,
	[START_DATE] [date] NOT NULL,
	[END_DATE] [date] NULL,
	[VERSION] [numeric](10, 0) NOT NULL,
 CONSTRAINT [PK_PROJECT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[PROJECT_NUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PROJECT_EMPLOYEE]    Script Date: 10/6/2021 9:34:36 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PROJECT_EMPLOYEE](
	[PROJECT_ID] [numeric](19, 0) NOT NULL,
	[EMPLOYEE_ID] [numeric](19, 0) NOT NULL,
 CONSTRAINT [PK_PROJECT_EMPLOYEE] PRIMARY KEY CLUSTERED 
(
	[PROJECT_ID] ASC,
	[EMPLOYEE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GROUP]  WITH CHECK ADD  CONSTRAINT [FK_GROUP_EMPLOYEE] FOREIGN KEY([GROUP_LEADER_ID])
REFERENCES [dbo].[EMPLOYEE] ([ID])
GO
ALTER TABLE [dbo].[GROUP] CHECK CONSTRAINT [FK_GROUP_EMPLOYEE]
GO
ALTER TABLE [dbo].[PROJECT]  WITH CHECK ADD  CONSTRAINT [FK_PROJECT_GROUP] FOREIGN KEY([GROUP_ID])
REFERENCES [dbo].[GROUP] ([ID])
GO
ALTER TABLE [dbo].[PROJECT] CHECK CONSTRAINT [FK_PROJECT_GROUP]
GO
ALTER TABLE [dbo].[PROJECT_EMPLOYEE]  WITH CHECK ADD  CONSTRAINT [FK_PROJECT_EMPLOYEE_EMPLOYEE] FOREIGN KEY([EMPLOYEE_ID])
REFERENCES [dbo].[EMPLOYEE] ([ID])
GO
ALTER TABLE [dbo].[PROJECT_EMPLOYEE] CHECK CONSTRAINT [FK_PROJECT_EMPLOYEE_EMPLOYEE]
GO
ALTER TABLE [dbo].[PROJECT_EMPLOYEE]  WITH CHECK ADD  CONSTRAINT [FK_PROJECT_EMPLOYEE_PROJECT] FOREIGN KEY([PROJECT_ID])
REFERENCES [dbo].[PROJECT] ([ID])
GO
ALTER TABLE [dbo].[PROJECT_EMPLOYEE] CHECK CONSTRAINT [FK_PROJECT_EMPLOYEE_PROJECT]
GO
USE [master]
GO
ALTER DATABASE [ELCA_PIM_TEST] SET  READ_WRITE 
GO
