//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.ProjectList {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProjectListRe {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectListRe() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.ProjectList.ProjectListRe", typeof(ProjectListRe).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project number, name, customer name.
        /// </summary>
        public static string CategoryFilterHolder_Label {
            get {
                return ResourceManager.GetString("CategoryFilterHolder_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close_WordLabel {
            get {
                return ResourceManager.GetString("Close_WordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm_WordLabel {
            get {
                return ResourceManager.GetString("Confirm_WordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this project?.
        /// </summary>
        public static string ConfirmDelete_Warning {
            get {
                return ResourceManager.GetString("ConfirmDelete_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete these project?.
        /// </summary>
        public static string ConfirmMultipleDelete_Warning {
            get {
                return ResourceManager.GetString("ConfirmMultipleDelete_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer_Header {
            get {
                return ResourceManager.GetString("Customer_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete_Header {
            get {
                return ResourceManager.GetString("Delete_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete_WordLabel {
            get {
                return ResourceManager.GetString("Delete_WordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected items.
        /// </summary>
        public static string DeleteSelectedItems_Label {
            get {
                return ResourceManager.GetString("DeleteSelectedItems_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID_Header {
            get {
                return ResourceManager.GetString("ID_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items selected.
        /// </summary>
        public static string ItemSelected_Label {
            get {
                return ResourceManager.GetString("ItemSelected_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name_Header {
            get {
                return ResourceManager.GetString("Name_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following projects couldn&apos;t be deleted due to its status:.
        /// </summary>
        public static string ProjectCantBeDeleted_Label {
            get {
                return ResourceManager.GetString("ProjectCantBeDeleted_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project List.
        /// </summary>
        public static string ProjectList_Label {
            get {
                return ResourceManager.GetString("ProjectList_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string ProjectNumber_Header {
            get {
                return ResourceManager.GetString("ProjectNumber_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects found: .
        /// </summary>
        public static string ProjectsFoundLabel {
            get {
                return ResourceManager.GetString("ProjectsFoundLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string ProjectStatusFinished_Label {
            get {
                return ResourceManager.GetString("ProjectStatusFinished_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Status.
        /// </summary>
        public static string ProjectStatusHolder_Label {
            get {
                return ResourceManager.GetString("ProjectStatusHolder_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress.
        /// </summary>
        public static string ProjectStatusInProgress_Label {
            get {
                return ResourceManager.GetString("ProjectStatusInProgress_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string ProjectStatusNew_Label {
            get {
                return ResourceManager.GetString("ProjectStatusNew_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned.
        /// </summary>
        public static string ProjectStatusPlanned_Label {
            get {
                return ResourceManager.GetString("ProjectStatusPlanned_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Search.
        /// </summary>
        public static string ResetSearch_Label {
            get {
                return ResourceManager.GetString("ResetSearch_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search_Label {
            get {
                return ResourceManager.GetString("Search_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate_Header {
            get {
                return ResourceManager.GetString("StartDate_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status_Header {
            get {
                return ResourceManager.GetString("Status_Header", resourceCulture);
            }
        }
    }
}
